version: '3'
services:
  app:
    image: node:alpine
    container_name: app_container
    entrypoint: /bin/sh
    ports:
     - "8080:8080"
    working_dir: /srv/app
    volumes:
     - type: bind
       source: ./
       target: /srv/app
    tty: true
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./api:/data
    restart: unless-stopped
  
